name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop,main ]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build all substreams'
        run: ./build-all.sh
